/**
 * ============================================
 *  WHATSAPP NOTIFIER (TWILIO OFFICIAL API)
 * ============================================
 *  Sends a summary of the highest matching jobs
 *  directly to the candidate's WhatsApp using
 *  Twilio's Sandbox API.
 * ============================================
 */

/**
 * Send job summary alert via Twilio WhatsApp API.
 * @param {object[]} jobs - Filtered job list
 * @param {object} config - Configuration object
 */
export async function sendWhatsAppSummary(jobs, config) {
  const accountSid = config.twilioAccountSid;
  const authToken = config.twilioAuthToken;
  const fromNum = config.twilioFrom || 'whatsapp:+14155238886'; // Twilio Sandbox default
  const toNum = config.twilioTo;

  if (!accountSid || !authToken || !toNum || accountSid === 'your_twilio_account_sid_here') {
    console.log('⚠️  Twilio WhatsApp parameters not configured. Skipping WhatsApp alert.');
    return;
  }

  const topJobs = jobs.slice(0, 5); // Format only top 5 jobs for readability
  if (topJobs.length === 0) {
    console.log('   No matching jobs to report via WhatsApp. Skipping.');
    return;
  }

  // Format message text
  let text = `🎯 *Daily Job Hunt Report — ${new Date().toLocaleDateString('en-IN', { month: 'short', day: 'numeric' })}*\n`;
  text += `Found *${jobs.length}* new full-time positions matching your profile.\n\n`;

  topJobs.forEach((job, index) => {
    text += `*${index + 1}. ${job.title}*\n`;
    text += `🏢 ${job.company}  |  🎯 ${job.atsScore}% Match\n`;
    text += `💰 ${job.salaryRange}  |  📍 ${job.location.split(',')[0]}\n`;
    text += `🔗 Link: ${job.applyLink}\n\n`;
  });

  if (jobs.length > 5) {
    text += `...and *${jobs.length - 5} more* roles.`;
  }

  text += `\n📧 Detailed report sent to *${config.emailTo}*.\n`;
  text += `_Generated by Daily Job Hunter Agent_`;

  // Base64 encode credentials for Basic Auth (native in Node.js)
  const authHeader = 'Basic ' + Buffer.from(`${accountSid}:${authToken}`).toString('base64');

  // Construct URL-encoded payload for Twilio REST API
  const bodyParams = new URLSearchParams({
    From: fromNum,
    To: toNum,
    Body: text
  });

  console.log('📨 Sending WhatsApp notification via Twilio REST API...');
  try {
    const response = await fetch(
      `https://api.twilio.com/2010-04-01/Accounts/${accountSid}/Messages.json`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          'Authorization': authHeader
        },
        body: bodyParams.toString()
      }
    );

    if (response.ok) {
      console.log('   ✅ WhatsApp alert sent successfully via Twilio!');
    } else {
      const errJson = await response.json();
      console.warn(`   ⚠️ Twilio API returned error status ${response.status}: ${errJson.message || 'Unknown Error'}`);
    }
  } catch (error) {
    console.warn(`   ⚠️ Twilio network error: ${error.message}`);
  }
}
